# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20170715_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='tag',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
